# Generated by Django 4.2.4 on 2023-08-24 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('timesheet_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('day_type', models.CharField(choices=[('working', 'Working'), ('sickleave', 'Sick Leave'), ('personalleave', 'Personal Leave'), ('holiday', 'Holiday'), ('projectholiday', 'Project Holiday')], default=('working', 'Working'), max_length=15)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
