# Generated by Django 4.2.4 on 2023-08-25 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTimesheet',
            fields=[
                ('date1', models.DateField()),
                ('date2', models.DateField()),
                ('date3', models.DateField()),
                ('date4', models.DateField()),
                ('date5', models.DateField()),
                ('hours_worked1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hours_worked2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hours_worked3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hours_worked4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hours_worked5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description1', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
                ('description3', models.TextField(blank=True)),
                ('description4', models.TextField(blank=True)),
                ('description5', models.TextField(blank=True)),
                ('day_type1', models.CharField(choices=[('working', 'Working'), ('sickleave', 'Sick Leave'), ('personalleave', 'Personal Leave'), ('holiday', 'Holiday'), ('projectholiday', 'Project Holiday')], default='working', max_length=15)),
                ('day_type2', models.CharField(choices=[('working', 'Working'), ('sickleave', 'Sick Leave'), ('personalleave', 'Personal Leave'), ('holiday', 'Holiday'), ('projectholiday', 'Project Holiday')], default='working', max_length=15)),
                ('day_type3', models.CharField(choices=[('working', 'Working'), ('sickleave', 'Sick Leave'), ('personalleave', 'Personal Leave'), ('holiday', 'Holiday'), ('projectholiday', 'Project Holiday')], default='working', max_length=15)),
                ('day_type4', models.CharField(choices=[('working', 'Working'), ('sickleave', 'Sick Leave'), ('personalleave', 'Personal Leave'), ('holiday', 'Holiday'), ('projectholiday', 'Project Holiday')], default='working', max_length=15)),
                ('day_type5', models.CharField(choices=[('working', 'Working'), ('sickleave', 'Sick Leave'), ('personalleave', 'Personal Leave'), ('holiday', 'Holiday'), ('projectholiday', 'Project Holiday')], default='working', max_length=15)),
                ('timesheet_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('timesheet_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('day_type', models.CharField(choices=[('working', 'Working'), ('sickleave', 'Sick Leave'), ('personalleave', 'Personal Leave'), ('holiday', 'Holiday'), ('projectholiday', 'Project Holiday')], default=('working', 'Working'), max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
